### PR TITLE
Update org.apache.sshd to match jenkins core version

### PR DESCRIPTION
**Pull request by paladox**
See https://github.com/jenkinsci/jenkins/pull/2662

### CODE REVIEW

**Comment by jglick** [comment]
This has since moved on to official release versions so I think this PR is obsolete.

**Comment by paladox** [comment]
Hmm it still shows 0.12.0 in pom on master.

**Comment by paladox** [comment]
Should i update to 1.6.0?

**Comment by oleg-nenashev** [comment]
It has been superseded by https://github.com/jenkinsci/ssh-credentials-plugin/pull/31 from what I see.
Thanks for raising this concern @paladox !

**Pull request closed without merging**
