### PR TITLE
Update FindBugs version, enable XML outputs

### PR DESCRIPTION
**Pull request by oleg-nenashev**
- [x] Reconfigure pom.xml
- [x] Enable FindBugs on https://jenkins.ci.cloudbees.com/job/plugins/job/ssh-credentials-plugin/
- [x] Fix important issues

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
@reviewbybees
The code is clean, ready for the merge

**Comment by varmenise** [comment]
:bee:

**Comment by oleg-nenashev** [comment]
Thanks Valentina

**Comment by KostyaSha** [comment]
:-1:

**Pull request merged**
