### PR TITLE
Faсelift towards the 1.14 release

### PR DESCRIPTION
**Pull request by oleg-nenashev**
- [x] Update Plugin pom to the recent version
- [x] Use 1.625.3 as a minimum Jenkins core version
- [x] Use newer JSch version to align the version with one proposed in #19 
- [x] Add 2 new maintainers

@stephenc Could you please confirm adding maintainers? In such case I will do the rest.

@reviewbybees @dwnusbaum

### CODE REVIEW

**Comment by dwnusbaum** [comment]
@oleg-nenashev The Findbugs error on the Linux-2.89.1 build existed before this PR, but maybe it makes sense to fix it here since you're doing a facelift anyway?

> [INFO] Redundant nullcheck of jenkins.model.Jenkins.getInstance(), which is known to be non-null in com.cloudbees.jenkins.plugins.sshcredentials.SSHAuthenticator.lookupFactories() [com.cloudbees.jenkins.plugins.sshcredentials.SSHAuthenticator] Redundant null check at SSHAuthenticator.java:[line 235] RCN_REDUNDANT_NULLCHECK_OF_NONNULL_VALUE

**Comment by oleg-nenashev** [comment]
Test failure seems to be related:

```
java.io.IOException: Remote call on slave0 failed
at hudson.remoting.Channel.call(Channel.java:916)
at com.cloudbees.jenkins.plugins.sshcredentials.impl.TrileadSSHPasswordAuthenticatorTest.testSlave(TrileadSSHPasswordAuthenticatorTest.java:180)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
at org.jvnet.hudson.test.JenkinsRule$1.evaluate(JenkinsRule.java:548)
at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.AssertionError:
Expected: is <true>
but: was <false>
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:956)
at org.junit.Assert.assertThat(Assert.java:923)
at com.cloudbees.jenkins.plugins.sshcredentials.impl.TrileadSSHPasswordAuthenticatorTest$RemoteConnectionTest.call(TrileadSSHPasswordAuthenticatorTest.java:206)
at com.cloudbees.jenkins.plugins.sshcredentials.impl.TrileadSSHPasswordAuthenticatorTest$RemoteConnectionTest.call(TrileadSSHPasswordAuthenticatorTest.java:190)
at hudson.remoting.UserRequest.perform(UserRequest.java:207)
at hudson.remoting.UserRequest.perform(UserRequest.java:53)
at hudson.remoting.Request$2.run(Request.java:358)
at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:72)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
... 1 more
Suppressed: hudson.remoting.Channel$CallSiteStackTrace: Remote call to slave0
```

**Comment by oleg-nenashev** [comment]
Actually, I was able to reproduce it

**Comment by oleg-nenashev** [comment]
Updated in the merge PR. Was a bad idea, I'd guess. If it does not build, feel free to take over an continue the implementation. No immediate plan to work on it.

**Comment by jglick** [comment]
Some of this already done in #39; @jvz care to pick up any remaining stuff?

**Comment by oleg-nenashev** [comment]
CC @jenkinsci/java11-support

**Pull request merged**
