### PR TITLE
Make trilead-api as optional as it contains some algo users may no want to use

### PR DESCRIPTION
**Pull request by olamy**
Signed-off-by: Olivier Lamy <olamy@apache.org>

### Testing done

```[tasklist]
### Submitter checklist
- [ ] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [ ] Ensure that the pull request title represents the desired changelog entry
- [ ] Please describe what you did
- [ ] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue
```

### CODE REVIEW

**Review by jglick — APPROVED** [review]
And conversely I see that `mina-sshd-api-core` lists `ssh-credentials` as an `optional` dep. (It uses `@Extension(optional = true)` which would better be switched to `@OptionalExtension` as here, to avoid warnings on startup in the unlikely case `ssh-credentials` is not in fact enabled.)

**Comment by Dohbedoh** [comment]
Shouldn't the trilead authenticator implementation eventually be moved to trilead-api plugin ? Like it is the case for [Jsch](https://github.com/jenkinsci/ssh-credentials-plugin/pull/152) and mina-sshd.

**Comment by olamy** [comment]
> Shouldn't the trilead authenticator implementation eventually be moved to trilead-api plugin ? Like it is the case for Jsch, see #152, and mina-sshd.

@Dohbedoh very good idea. Do you have time to take care of this? If not, let me know and I will.

**Comment by Dohbedoh** [comment]
I can take a look. But will need some coordination / release plan between those 2 plugins to avoid circular dependencies.

**Comment by olamy** [comment]
> I can take a look. But will need some coordination / release plan between those 2 plugins to avoid circular dependencies.

sounds good. We can coordinate at the pub :)

**Comment by basil** [comment]
After this PR, in the context of https://github.com/jenkinsci/acceptance-test-harness

```
import com.cloudbees.jenkins.plugins.sshcredentials.SSHAuthenticatorFactory
ExtensionList.lookup(SSHAuthenticatorFactory.class)
```

returns the empty list instead of the two Trilead implementations, causing https://github.com/jenkinsci/acceptance-test-harness/issues/1539 and https://github.com/jenkinsci/acceptance-test-harness/issues/1540 (39 new ATH failures).

**Pull request merged**
