### PR TITLE
Update baseline to 2.282, fixes PCT (detached ssh plugin)

### PR DESCRIPTION
**Pull request by timja**
See https://github.com/jenkinsci/bom/pull/449 and https://github.com/jenkinsci/jenkins/pull/5049

Tests fail on 2.282 without this change

We will need a release for bom please

cc @jvz @jglick @car-roll

### CODE REVIEW

**Review by car-roll — APPROVED** [review]

**Review by jvz — APPROVED** [review]

**Comment by jvz** [comment]
Released

**Comment by sbeaulie** [comment]
This is breaking installing of Git client plugin
```
java.io.IOException: Failed to load: Jenkins Git client plugin (3.6.0)

    Update required: SSH Credentials Plugin (1.17.4) to be updated to 1.18.1 or higher
```
but I'm on LTS 2.277.1 and 1.18.1 requires 2.282

**Comment by MarkEWaite** [comment]
@sbeaulie you'll need to describe the steps you're taking that are generating the message "Failed to load".  I would guess that you might be using install-plugins.sh instead of plugin installation manager.

**Comment by hashar** [comment]
The 2.282 dependency prevent the plugin from being installed on the current LTS (2.277.2) :-\

**Comment by MarkEWaite** [comment]
> The 2.282 dependency prevent the plugin from being installed on the current LTS (2.277.2) :-\

That's intentional.  The required changes are not available in 2.277.2.  The required changes are being used with the weekly releases and will be be available in the June LTS of 2.289.1.

**Comment by bashbers** [comment]
> you could read the PR, which clearly states why

Ah I was reading through the commits themselves, did not see the PR. My bad.

**Comment by daniel-beck** [comment]
Could the folks commenting here tell us how they manage plugins? It's not clear to me why this is causing problems, all of our tools should select only compatible versions (and if not, there's a bug).

**Pull request merged**
